#!/bin/bash

#SBATCH --partition=long
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=5:00:00
#SBATCH --cpus-per-task=4
#SBATCH -o /network/scratch/f/faisal.mohamed/slurm-%j.out  # Write the log on scratch

# 1. Load your environment
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia
export WANDB_DIR=$SCRATCH
export WANDB_MODE=online
module load anaconda/3
conda activate /home/mila/f/faisal.mohamed/.conda/envs/diffuser


# 4. Launch your job
#python $1 $2 $3 $4 $5 $6 $7 $8 ${9} ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21}
python scripts/train.py --dataset halfcheetah-medium-expert-v2
