add_training_conditioning: true
checkpointing_freq: 20000
env_id: hopper-medium-expert-v2
eval_batch_size: 1
gradient_accumulation_steps: 1
horizon: 128
hub_private_repo: false
image_size: 128
learning_rate: 0.0001
lr_warmup_steps: 500
mixed_precision: fp16
n_train_step_per_epoch: 10000
n_train_steps: 200000
num_epochs: 50
num_train_timesteps: 100
output_dir: ddpm-butterflies-128
overwrite_output_dir: true
push_to_hub: true
render_freq: 4200
save_image_epochs: 10
save_model_epochs: 30
seed: 0
train_batch_size: 16
use_conditioning_for_sampling: true
use_sample_hf_for_render: false
